# Generated by Django 2.2.10 on 2020-02-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="hgfhgf",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="jjkjkjkjhkj",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="test",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="testtt",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
