# Generated by Django 2.2.10 on 2020-02-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200210_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
